import type { Catalog } from "./schema.ts";

export type ConsentMessages = Pick<
  Catalog["dynamic"],
  "consentAccepted" | "consentRejected" | "consentOff"
>;
export interface RuntimeCopy {
  consent: ConsentMessages;
  home?: {
    dynamic: Omit<Catalog["dynamic"], keyof ConsentMessages>;
    gallery: Catalog["home"]["gallery"];
  };
}

let cached: RuntimeCopy | undefined;
/** Reads only the typed payload generated by BaseLayout for this page. */
export function getRuntimeCopy(): RuntimeCopy {
  if (cached) return cached;
  const node = document.getElementById("locale-messages");
  if (!node?.textContent) throw new Error("Missing page translations");
  cached = JSON.parse(node.textContent) as RuntimeCopy;
  return cached;
}
